# Numpy Arrays

This Notebook includes the following contents:

* Introduction to the Numpy Library.
* Installation Instructions.
* Import Numpy.
* Numpy Arrays.
  1. Creating NumPy Arrays.

     - From a Python List or Nested List.
     - From Built-in Methods (arange, zeros and ones, linspace, eye, identity).
     - From Random Built-in Methods to create random number arrays (rand, randn, randint)

  2. Size, Shape and Reshape.

  3. Built-in Methods (max, argmax, min, argmin)


# Introduction to the Numpy Library.

NumPy (or Numpy) is a **Linear Algebra Library for Python**, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation.

We will only learn the basics of NumPy, to get started we need to install it!

# Installation Instructions

It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:
    
    conda install numpy
    
If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)

    pip install numpy



---



# Import Numpy

Once you've installed NumPy you can import it as a library:

In [1]:
import numpy as np

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices.

`Vectors` are strictly 1-d arrays.

`Matrices` are 2-d (but you should note a matrix can still have only one row or one column).


---



# Creating NumPy Arrays


Let's begin our introduction by exploring how to create NumPy arrays.

### From a Python List or Nested List

`We can create an array by directly converting a list or list of lists`

In [2]:
import numpy as np

In [3]:
# From List

my_list = [1,2,3,4,5,6]
print(my_list)
print(np.array(my_list))

[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]


In [4]:
# From Nested List

my_matrix = [[1,2,3],[4,5,6]]
print(my_matrix)
print(np.array(my_matrix))

[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]


Task #1:

Create a NumPy array from a given list: [5, 10, 15, 20, 25].


---



In [5]:
# Task 1

list1 = [5,10,15,20,25]
print(np.array(list1))

[ 5 10 15 20 25]


In [6]:
my_list = [[1, 2], [3, 4], [5, 6]]
np_array = np.array(my_list)

print(np_array)

[[1 2]
 [3 4]
 [5 6]]


Task #2:

Create a 3x5 NumPy array.


---



In [8]:
# Task 2

list1 = [[5,10,15],[20,25,30],[35,40,45],[50,55,60],[65,70,75]]
array3_5 = np.array(list1)
print(array3_5)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]
 [50 55 60]
 [65 70 75]]


In [9]:
arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


### From Built-in Methods

There are lots of built-in ways to generate Arrays

#### arange



`Return evenly spaced values within a given interval.`

In [10]:
# (Start, End)
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# (Start, End, Step)
np.arange(0,11,3)

array([0, 3, 6, 9])

#### zeros and ones

`Generate arrays of zeros or ones`

In [ ]:
np.zeros(3)           # One raw

array([0., 0., 0.])

In [ ]:
np.zeros((4,5))       # Multi raws and columns

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(3)            # One raw

array([1., 1., 1.])

In [ ]:
np.ones((3,3))        # Multi raws and columns

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.ones((5,1))        # One column

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

#### linspace


`Return evenly spaced numbers over a specified interval.`

In [ ]:
#That is, print an array that starts with 0 and ends with 10, provided that it contains 5 numbers
np.linspace(0,10,5)     # Here the end is printed

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.linspace(0,10,21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

#### eye

`Creates an identity matrix`

In [ ]:
# Identity matrix: sometimes called a unit matrix, is a diagonal matrix with all its diagonal elements equal to 1 , and zeroes everywhere else.
1 , 0 , 0
0 , 1 , 0
0 , 0 , 1

(0, 0, 1)

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Built-in Methods Tasks

Task #3:

Generate an array of 10 even numbers starting from 2.

In [12]:
# Task 3

arr_even = np.arange(2,11,2)
print(arr_even)

[ 2  4  6  8 10]


In [13]:
arr = np.arange(0, 21,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18 20]


Task #4:

Create a 4x4 matrix filled with zeros.

In [15]:
# Task 4
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Task #5:

Create a vector of 5 ones.

In [17]:
# Task 5
np.ones(5)

array([1., 1., 1., 1., 1.])

Task #6:

Generate 6 evenly spaced numbers between 0 and 30.

In [19]:
# Task 6
np.linspace(0,30,6)

array([ 0.,  6., 12., 18., 24., 30.])

Task #7:

Create a 3x3 identity matrix

In [20]:
# Task 7
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### From Random Built-in Methods

Numpy also has lots of ways to create random number arrays:

#### rand

``Create an array of the given shape and populate it with random samples from a uniform distribution
over [0, 1).``




In [21]:
import numpy as np

In [22]:
np.random.rand(2)

array([0.72095158, 0.93817132])

In [23]:
np.random.rand(2,5)

array([[0.93496993, 0.80060848, 0.72977245, 0.10934926, 0.84826152],
       [0.63238295, 0.77569251, 0.09073845, 0.87786702, 0.55832662]])

#### randn

`Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:`

In [ ]:
np.random.randn(2)

array([-0.84410052, -0.2726015 ])

In [24]:
np.random.randn(5,2)

array([[ 1.21266089, -0.05191987],
       [ 1.03311618, -0.18398131],
       [ 0.25500933, -0.64219001],
       [ 0.04826151, -0.51044358],
       [ 0.66827111,  0.0351285 ]])

#### randint

`Return random integers from **low** (inclusive) to **high** (exclusive).`

In [25]:
np.random.randint(1,100,5)

array([35, 21, 46, 21, 96], dtype=int32)

In [26]:
np.random.randint(1,100,(4,10))

array([[59, 97, 87, 34, 96,  5, 85, 69, 82, 53],
       [54, 69, 13, 41, 81, 11, 67, 47, 15, 40],
       [55, 70, 64,  1, 92, 29, 96, 42, 91, 11],
       [35, 27,  5, 63, 47, 34, 70, 25,  2, 47]], dtype=int32)

#### Random Built-in Methods Tasks

Task #8:

Create an array of 5 random numbers from the uniform distribution.

In [29]:
# Task 8

raand = np.random.rand(5)
raand

array([0.56590392, 0.28396497, 0.5961023 , 0.92470611, 0.6506015 ])

Task #9:

Create a 3x3 matrix of random numbers from the standard normal distribution.

In [31]:
# Task 9
raand1 = np.random.randn(3,3)
raand1

array([[-0.55131337,  1.04556426, -1.53056923],
       [ 2.22428911,  0.54717354, -0.79611119],
       [ 0.44952148, -0.30913312, -1.10751714]])

Task #10:

Generate 5*5 random integers between 10 and 50.

In [42]:
# Task 10
raand_int = np.random.randint(10,50,(5,5))
raand_int

array([[46, 48, 29, 19, 45],
       [20, 40, 46, 36, 25],
       [33, 10, 29, 17, 19],
       [18, 42, 19, 16, 40],
       [13, 42, 43, 19, 23]], dtype=int32)

# Size, Shape and Reshape

## Size

In [35]:
arr_1 = np.random.randint(10, 20, (5,5), dtype=int)

In [36]:
arr_1

array([[15, 13, 11, 10, 11],
       [13, 18, 16, 17, 11],
       [17, 17, 14, 16, 19],
       [14, 18, 18, 15, 17],
       [14, 15, 18, 13, 14]], dtype=int32)

In [37]:
arr_1.size

25

## Shape

`Shape is an attribute that arrays have (not a method)`

In [38]:
arr_1.shape

(5, 5)

## Reshape

In [39]:
arr_1.reshape(1,25)

array([[15, 13, 11, 10, 11, 13, 18, 16, 17, 11, 17, 17, 14, 16, 19, 14,
        18, 18, 15, 17, 14, 15, 18, 13, 14]], dtype=int32)

In [40]:
arr_1.reshape(1,25).shape

(1, 25)

Task #11:

Generate an array of 12 numbers and then reshape it into a 3x4 matrix.

In [44]:
# Task 11
arr_1 = np.random.randint(1, 50, 12, dtype=int)
print(arr_1)
print("Shape: ", arr_1.shape)
print("Reshaped Array: \n",arr_1.reshape(3,4))

[16 39 15 26 10  3 47 18 17 34 25 36]
Shape:  (12,)
Reshaped Array: 
 [[16 39 15 26]
 [10  3 47 18]
 [17 34 25 36]]


# Built-in Methods

## max, min, argmax, argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [45]:
arr_1 = np.random.randint(10, 20, (5,5), dtype=int)
print(arr_1)

[[16 10 19 17 15]
 [16 11 13 13 12]
 [19 12 15 11 14]
 [14 13 13 16 19]
 [16 17 12 11 19]]


In [46]:
print(arr_1.max())

19


In [47]:
print(arr_1.argmax())

2


In [48]:
print(arr_1.min())

10


In [49]:
print(arr_1.argmin())

1


In [50]:
import numpy as np
numbers = np.array([34, 56, 23, 89, 12, 48, 67])
max_value, max_index = numbers.max(), numbers.argmax()
min_value, min_index = numbers.min(), numbers.argmin()
print("Maximum value:", max_value, "at index:", max_index)
print("Minimum value:", min_value, "at index:", min_index)

Maximum value: 89 at index: 3
Minimum value: 12 at index: 4


Task #12:

Exercise: Given the array numbers = np.array([34, 56, 6, 89, 12, 98, 67]), find the maximum, minimum, and the index of both in the array.

In [59]:
# Task 12
array_number = np.array([34,56,6,89,12,98,67])

max_val , max_index = array_number.max() ,  array_number.argmax()
min_val , min_index = array_number.min() , array_number.argmin()

print("Maximum value:", max_val, "at index:", max_index)
print("Minimum value:", min_val, "at index:", min_index)


Maximum value: 98 at index: 5
Minimum value: 6 at index: 2


### dtype

You can also grab the data type of the object in the array:

In [51]:
numbers

array([34, 56, 23, 89, 12, 48, 67])

In [52]:
numbers.dtype

dtype('int64')

In [53]:
v = [[1, "batool"], [2, True]]
array_v = np.array(v)
array_v

array([['1', 'batool'],
       ['2', 'True']], dtype='<U21')

In [54]:
array_v.dtype

dtype('<U21')

# Great Job 🚀