# Numpy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

This Notebook includes the following contents:

* Bracket Indexing and Selection
* Broadcasting
* Indexing a 2D array (matrices)
* Fancy Indexing
* Selection

# Bracket Indexing and Selection

The simplest way to pick one or some elements of an array looks very similar to python list.

In [1]:
import numpy as np

In [2]:
#Creating sample array
arr = np.arange(1,11)

In [3]:
#Show
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
#Get a value at an index
arr[8]

np.int64(9)

In [5]:
#Get values in a range
arr[1:5]

array([2, 3, 4, 5])

In [6]:
#Get values in a range
arr[0:5]

array([1, 2, 3, 4, 5])

In [7]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[0:7:2]

array([1, 3, 5, 7])

# Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast

In [9]:
# List
lst = [1, 5, 7, 2, 5, 9]
lst[1] = 8
lst

[1, 8, 7, 2, 5, 9]

In [ ]:
# Error: just for clarification
lst[1:3] = 8 # error must assign iterable to extended slice
lst

In [ ]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [ ]:
# Reset array
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [ ]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [ ]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
arr_copy[1:3] = 100
arr_copy

array([ 99, 100, 100,  99,  99,  99,   6,   7,   8,   9,  10])

In [ ]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [ ]:
x = ([5,10,15],[20,25,30],[35,40,45])
type(x)

tuple

In [ ]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
#Indexing row, all columns
arr_2d[0]


array([ 5, 10, 15])

In [ ]:
arr_2d[1,1]

np.int64(25)

In [ ]:
arr_2d[1][1]

np.int64(25)

In [ ]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

np.int64(20)

In [ ]:
# Getting individual element value
arr_2d[1,0]

In [ ]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [ ]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [ ]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
#Shape bottom row
arr_2d[2,1:]

array([40, 45])

In [ ]:
arr_2d[0:2,0:2]

array([[ 5, 10],
       [20, 25]])

In [ ]:
arr_2d[1,1:]

array([25, 30])

# Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array

In [ ]:
import numpy as np

In [ ]:
#Set up matrix
arr2d = np.zeros((10,9))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
#Length of array
arr_length = arr2d.shape[1]
arr_length

9

In [ ]:
arr2d[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
arr2d[1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i

arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Fancy indexing allows the following

In [ ]:
arr2d[[0,3,5]]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [ ]:
arr2d[[5,0,6]]

array([[5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6.]])

In [ ]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [ ]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7.]])

# Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [ ]:
x= 10
if x<5:
  print("hi")

In [ ]:
arr = np.arange(1,11)
print(arr)


[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
print(arr[arr<4])

[1 2 3]


In [ ]:
x = arr > 4
arr[x] #return only the values in arr where x is True

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
bool_arr = arr<4

In [ ]:
bool_arr

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [ ]:
arr[arr<4]

array([1, 2, 3])

In [ ]:
arr[bool_arr]

array([1, 2, 3])

In [ ]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# Great Job 🚀